### ISSUE TITLE
getAppendersMap is private

### ISSUE THREAD

**Issue by mathewbergt** [coldbox-modules/cbox-debugger#16]
The documentation demonstrates how to load `ColdBoxTracerAppender` programatically, but `logbox.getAppendersMap` has private access.

```javascript
var appenders = logBox.getAppendersMap( 'tracer' );
```

Is it possible to obtain the appenders map without access to `getAppendersMap`?

**Comment by gusmeister** [comment]
I also ran into this after following the logbox 2.0 docs. Changed getAppendersMap to public and all good.

Note the docs also refer to a number of appenders eg ColdBoxTracerAppender, AsyncFileAppender but they don't exist in the appenders package.

**Comment by elpete** [comment]
This pull request should fix it: https://github.com/ColdBox/coldbox-platform/pull/276
